### ISSUE TITLE
FTManager does not display TrueType font list when system language is set to Polish

### ISSUE THREAD

**Issue by subocz** [deadwood2/AROS#122]
When we change the system language to Polish, FTManager does not display a list of TrueType fonts. The reason is a wrong translation in polish/system/system/FTManager.catalog, which translates the names of system directories without the need.

Possible solution, update the translation to the following:

https://github.com/subocz/ftmanager/blob/master/polish.ct

**Comment by deadwood2** [comment]
Fixed in 7422e70601f2c9ec71bd2a304b4a9f3da643fa60
