### ISSUE TITLE
You can access a drawer icon even if the directory assigned to it does not exist

### ISSUE THREAD

**Issue by subocz** [deadwood2/AROS#125]
If you delete a directory but do not delete the .info file, Wanderer will still display the directory icon that you can enter (if it is a drawer type) and try to copy something to it. This will result in the error message ‘Failed to lock path: …’, and the file will be copied one directory higher.

The desired behavior is that you cannot enter the drawer icon if the assigned directory does not exist.

**Comment by deadwood2** [comment]
Fixed in 8270dcff6d8b2f5b36dcb374790c05c15729a216 and f33513e197893b21098692daa72025f6a233ade9
