### ISSUE TITLE
DOS SameLock() does not correctly return LOCK_SAME_VOLUME

### ISSUE THREAD

**Issue by broadblues** [deadwood2/AROS#128]
When testing two locks DOS->SameLock() will only return LOCK_SAME if the locks are for the same file and never LOCK_SAME_VOLUME if the locks are on the same volume.

Looking at https://github.com/deadwood2/AROS/blob/master/rom/dos/samelock.c  I see there is a "logic error" in the code flow in that the test for LOCK_SAME_VOLUME only occurs if the result from dospaacket2() is ERROR_ACTION_UNKNOWN thus ironically a filesystem that supports ACTION_SAME_LOCK will never return LOCK_SAME_VOLUME.

Also it would seem logical that given the initial test for SameDevice() the default return value of the function should be LOCK_SAME_VOLUME as same device => same volume

**Comment by deadwood2** [comment]
Ok, which version of AROS you need/are using (i386, x86_64, m68k) and which filesystem? Additionally how urgent this fix is for you?

**Comment by broadblues** [comment]
I'm working with m68k AROS and the UAE drawer filesystem. (proper name escapes my memory!)

I have a work around for my specific use case. I mainly wanted to report the issue.

**Comment by deadwood2** [comment]
Ok, got it. I'll look into fixing that in coming weeks.
