### ISSUE TITLE
[VirtualBox 7.0.12/pcnet32.device] AROS loses network connection, "no buffer space available"

### ISSUE THREAD

**Issue by deadwood2** [deadwood2/AROS#138]
This is a bug report specific to pcnet32.device on VirtualBox 7.0.12, derived from this bug:

https://github.com/deadwood2/AROS/issues/132

**Comment by deadwood2** [comment]
@ncafferkey I tracked down issues with pcnet32 and would like to ask for your opinion.

Basically when the TX_Int code detects that all hardware tx buffers are used, it stops further processing, which then results will all buffers being exhausted on AROSTCP side (IOs being send to driver but never replied). Here is a link to specif code that stops processing:

https://github.com/deadwood2/AROS/blob/fb3f28e17371646c90a5e18a4f5f52b9b8827f8f/workbench/devs/networks/pcnet32/unit.c#L586

My question is: is it a possible situation that hardware will indeed not process requests in time and driver simply needs to account for that? If I disable code in question, then the TX_Int will busy loop for a 50-500 iterations, then hardware releases a buffer and processing in the driver continues as it should. This "immediate" stopping that is now in code feels like an overkill.

I also check the rtl8169 drivers, which @subocz reported that does not have disconnection issue. The TX_Int is almost identical (I guess most of the drivers use the same template code), except for one detail: it never abandons process - if there are no hardware buffers, it just keeps spinning until some are freed.

**Comment by deadwood2** [comment]
A workaround/fix for this issue is implemented in https://github.com/deadwood2/AROS/commit/a78e105de811af5a5c40e719d7a0998e616c06f3

**Comment by ncafferkey** [comment]
Sorry, I only saw this now. It should be OK to stop processing new TX requests as long as they are turned on again at some point :-) What usually happens in our network drivers (or at least the ones I've worked on) is that TX processing resumes when an interrupt indicating completion of a previous TX frame occurs and the interrupt handler explicitly restarts processing.

**Comment by deadwood2** [comment]
Ah, now that sounds like a proper solution.
